BEGIN{
  FS=","
}
{
	print "\t<login id=\""$1"\" password=\""$2"\" delimiter=\"|\" error-detect=\"enabled\" institution=\""$3"\" checked_in_ok=\"1\">"
	print "\t\t<!-- General messages -->"
	print "\t\t<screen_msg_regex find=\"^.*Invalid password.*$\" replace=\"Feil passord\" />"
	print "\t\t<!-- Checkout screen messages we can translate directly -->"
	print "\t\t<screen_msg_regex find=\"Item checked out to another patron.*$\" replace=\"Materialet er lånt ut til en annen låner.\" />"
	print "\t\t<screen_msg_regex find=\"Item already checked out to you: renewing item.\" replace=\"Denne fornyes siden du allerede har lånt den.\" />"
	print "\t\t<screen_msg_regex find=\"Item was reserved for you.\" replace=\"Du hadde reservert denne.\" />"
	print "\t\t<screen_msg_regex find=\"Item is reserved for another patron upon return.\" replace=\"Materialet er reservert av en annen låner.\" />"
	print "\t\t<screen_msg_regex find=\"Item already checked out to another patron.  Please return item for check-in.\" replace=\"Materialet er allerede lånt ut til en annen låner. Vennligst returner det.\" />"
	print "\t\t<screen_msg_regex find=\"Outstanding Fines block issue.*\" replace=\"Du kan ikke låne grunnet utestående gebyrer.\" />"
	print "\t\t<screen_msg_regex find=\"Loan period reduced for high-demand item\" replace=\"Låneperioden er redusert pga stor etterspørsel\" />"
	print "\t\t<screen_msg_regex find=\"Item is on hold shelf for another patron\" replace=\"Materialet står til avhenting av en annen låner\" />"
	print "\t\t<screen_msg_regex find=\"Invalid Item\" replace=\"Ugyldig eksemplar\" />"
	print "\t\t<screen_msg_regex find=\"Invalid Patron\" replace=\"Ugyldig lånekort\" />"
	print "\t\t<screen_msg_regex find=\"Invalid cardnumber\" replace=\"Ugyldig lånekort\" />"
	print "\t\t<screen_msg_regex find=\"^.*Borrower.s card reported lost.*$\" replace=\"Lånekortet er meldt tapt. Vennligst kontakt personalet.\" />"
	print "\t\t<screen_msg_regex find=\"^.*Borrower has no valid address.*$\" replace=\"Feil i adresse. Vennligst kontakt personalet.\" />"
	print "\t\t<!-- Renew -->"
	print "\t\t<screen_msg_regex find=\"Item unavailable due to outstanding holds\" replace=\"Materialet er utilgjengelig pga ventende reservasjoner\" />"
	print "\t\t<screen_msg_regex find=\"Item has reached maximum renewals\" replace=\"Materialet kan ikke lånes flere ganger\" />"
	print "\t\t<screen_msg_regex find=\"NO_MORE_RENEWALS[\\:]*\" replace=\"Maks antall fornyelser oversteget.\" />"
	print "\t\t<!-- Missing screen messages in Koha and other quirks -->"
	print "\t\t<screen_msg_regex find=\"^.*Patron owes.+$\" replace=\"Du har utestående gebyrer - henvend deg til personalet.\" />"
	print "\t\t<screen_msg_regex find=\"^Patron Blocked$\" replace=\"Lånekortet er sperret - henvend deg til personalet.\" />"
	print "\t\t<screen_msg_regex find=\"AGE_RESTRICTION[\\:]*\" replace=\"\" />"
	print "\t\t<screen_msg_regex find=\"TOO_MANY_CHECKOUTS\" replace=\"For mange utlån\" />"
	print "\t\t<screen_msg_regex find=\"NOT_FOR_LOAN.*$\" replace=\"Materialet er ikke til utlån.\" />"
	print "\t\t<screen_msg_regex find=\"item_notforloan.*$\" replace=\"Materialet er ikke til utlån.\" />"
	print "\t\t<!-- Bug 15438 - Checking out an on-hold item sends holder's borrowernumber in AF (screen message) field. -->"
	print "\t\t<!-- gjelder også utlån av samme eksemplar to ganger -->"
	print "\t\t<screen_msg_regex find=\"^\d{1,}$\" replace=\"Materialet er allerede utlånt/reservert.\" />"
	print "\t\t<!-- Last resort -->"
	print "\t\t<screen_msg_regex find=\"Greetings from Koha.\" replace=\"Melding fra biblioteket:\" />"
	print "\t</login>"
}